import { User, Utensils, Hotel, Truck, Building2 } from 'lucide-react'

export const CUSTOMER_TYPE_CONFIG = {
  'องค์กร': {
    type: 'องค์กร',
    label: 'องค์กร',
    title: 'ลูกค้าองค์กร / บริษัท',
    icon: Building2,
    emoji: '🏢',
    themeColor: 'purple',
    badgeClass: 'bg-purple-100 text-purple-800 border-purple-200',
    headerBg: 'bg-purple-600 text-white',
    headerLightBg: 'bg-purple-50 text-purple-700 border-b border-purple-100',
    cardBorder: 'border-purple-200',
    cardBg: 'bg-gradient-to-br from-purple-50/50 via-white to-purple-50/20',
    avatarRing: 'ring-2 ring-purple-300 bg-purple-100 text-purple-700',
    iconColor: 'text-purple-600',
    dotColor: 'bg-purple-500',
    accentBorder: 'border-l-4 border-l-purple-500',
  },
  'ร้านอาหาร': {
    type: 'ร้านอาหาร',
    label: 'ร้านอาหาร',
    title: 'ลูกค้าร้านอาหาร / คาเฟ่',
    icon: Utensils,
    emoji: '🍽️',
    themeColor: 'amber',
    badgeClass: 'bg-amber-100 text-amber-800 border-amber-200',
    headerBg: 'bg-amber-500 text-white',
    headerLightBg: 'bg-amber-50 text-amber-700 border-b border-amber-100',
    cardBorder: 'border-amber-200',
    cardBg: 'bg-gradient-to-br from-amber-50/50 via-white to-amber-50/20',
    avatarRing: 'ring-2 ring-amber-300 bg-amber-100 text-amber-700',
    iconColor: 'text-amber-600',
    dotColor: 'bg-amber-500',
    accentBorder: 'border-l-4 border-l-amber-500',
  },
  'โรงแรม': {
    type: 'โรงแรม',
    label: 'โรงแรม',
    title: 'ลูกค้าโรงแรม / รีสอร์ต',
    icon: Hotel,
    emoji: '🏨',
    themeColor: 'sky',
    badgeClass: 'bg-sky-100 text-sky-800 border-sky-200',
    headerBg: 'bg-sky-600 text-white',
    headerLightBg: 'bg-sky-50 text-sky-700 border-b border-sky-100',
    cardBorder: 'border-sky-200',
    cardBg: 'bg-gradient-to-br from-sky-50/50 via-white to-sky-50/20',
    avatarRing: 'ring-2 ring-sky-300 bg-sky-100 text-sky-700',
    iconColor: 'text-sky-600',
    dotColor: 'bg-sky-500',
    accentBorder: 'border-l-4 border-l-sky-500',
  },
  'ขายส่ง': {
    type: 'ขายส่ง',
    label: 'ขายส่ง',
    title: 'ลูกค้าขายส่ง / ตัวแทน',
    icon: Truck,
    emoji: '📦',
    themeColor: 'emerald',
    badgeClass: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    headerBg: 'bg-emerald-600 text-white',
    headerLightBg: 'bg-emerald-50 text-emerald-700 border-b border-emerald-100',
    cardBorder: 'border-emerald-200',
    cardBg: 'bg-gradient-to-br from-emerald-50/50 via-white to-emerald-50/20',
    avatarRing: 'ring-2 ring-emerald-300 bg-emerald-100 text-emerald-700',
    iconColor: 'text-emerald-600',
    dotColor: 'bg-emerald-500',
    accentBorder: 'border-l-4 border-l-emerald-500',
  },
  'ทั่วไป': {
    type: 'ทั่วไป',
    label: 'ทั่วไป',
    title: 'ลูกค้าทั่วไป',
    icon: User,
    emoji: '👤',
    themeColor: 'slate',
    badgeClass: 'bg-slate-100 text-slate-700 border-slate-200',
    headerBg: 'bg-slate-600 text-white',
    headerLightBg: 'bg-slate-50 text-slate-700 border-b border-slate-100',
    cardBorder: 'border-gray-200',
    cardBg: 'bg-gradient-to-br from-gray-50/80 via-white to-gray-50/30',
    avatarRing: 'ring-2 ring-slate-300 bg-slate-100 text-slate-700',
    iconColor: 'text-slate-500',
    dotColor: 'bg-slate-400',
    accentBorder: 'border-l-4 border-l-slate-400',
  }
}

export function getCustomerTypeConfig(type) {
  if (!type) return CUSTOMER_TYPE_CONFIG['ทั่วไป']
  return CUSTOMER_TYPE_CONFIG[type] || CUSTOMER_TYPE_CONFIG['ทั่วไป']
}
